### ISSUE TITLE
Please add "success" in green.

### ISSUE THREAD

**Issue by mukhtorov712** [Bungeefan/logger#12]
I monitor requests and responses using a logger. In this case, I would like to use a green log for a successful request.

**Comment by Bungeefan** [comment]
I am guessing you are talking about the PrettyPrinter.

How would you indicate/label such a successful request?
Currently, colors are only dependent on the log level you are using.

**Comment by Bungeefan** [comment]
Without additional information, I am unfortunately not able to resolve this issue.
I am therefore going to close this issue.

**Comment by mukhtorov712** [comment]
I organized the processes of sending and receiving requests. I will show in the log that the received response was successful. I am currently using this log "Logger().i(response)" -> "blue".
I want to use something like "Logger().s(response)" -> "green". I did this by modifying the library, but I want it to be useful for others. Thank you.

**Comment by Bungeefan** [comment]
What is your **s** log level, and would it be sufficient to enable the configuration of the levelColors in `PrettyPrinter`?

You could also post your modification, so I can get a better understanding of your desired solution.

**Comment by Bungeefan** [comment]
Following up the #37 PR:

Unfortunately, I had to decline the proposed solution, because I don't think that a custom log level specific to your use case justifies adding it to the logger package.
I think you can still achieve a similar solution without introducing a new uncommon log level.

The addition would also lead to other considerations:
* What is with other custom but similar log levels that users might want to introduce (denied, failure, ...)?
* `success` isn't a common logger level (in fact, I haven't yet come across a single library using it)
* Which importance has "success"? Is it more important than `error` or less than `debug`? These are questions that we can't/won't and shouldn't answer for every user of this library!
* ... and so on

I hope you understand my concerns, and I am still open for further discussion and new ideas!
